import { eq, and, isNull, ne, inArray } from 'drizzle-orm'
import { db } from './db'
import { sessions } from './schema'
import type { Session } from './schema'
import { base64Encode } from './crypto/base64'
import { generateId } from './db-utils'

export type SessionKind = 'web' | 'cli' | 'token'

export const WEB_SESSION_TTL_MS = 30 * 24 * 60 * 60 * 1000
// CLI sessions are short-lived and roll on every successful request.
export const CLI_SESSION_TTL_MS = 30 * 60 * 1000
// After a rotation, the previous token stays valid briefly so an interrupted
// CLI (or a parallel request) isn't locked out mid-window.
export const PREV_TOKEN_GRACE_MS = 60 * 1000

// Long-lived access tokens ('token' kind, for headless machines): a stable
// bearer that never rolls. Lifetime is chosen at creation, 30 days to 2
// years, or "does not expire" - stored as a far-future sentinel so the
// requireAuth expiry check needs no special case.
export const TOKEN_MIN_DAYS = 30
export const TOKEN_MAX_DAYS = 730
export const TOKEN_NEVER_EXPIRES = new Date('9999-12-31T00:00:00.000Z')

export function tokenNeverExpires(expiresAt: Date): boolean {
  return expiresAt.getTime() >= TOKEN_NEVER_EXPIRES.getTime()
}

export function sessionTTL(kind: SessionKind): number {
  return kind === 'cli' ? CLI_SESSION_TTL_MS : WEB_SESSION_TTL_MS
}

async function newToken(): Promise<{ token: string; tokenHash: string }> {
  const tokenBytes = crypto.getRandomValues(new Uint8Array(32))
  const token = base64Encode(tokenBytes)
  const hashBuffer = await crypto.subtle.digest('SHA-256', tokenBytes)
  return { token, tokenHash: base64Encode(new Uint8Array(hashBuffer)) }
}

export async function createSession(
  userId: string,
  serverPubkey: string,
  encryptedOrgKeys: Record<string, string>,
  kind: SessionKind = 'web'
): Promise<{ token: string; sessionId: string; expiresAt: Date }> {
  const { token, tokenHash } = await newToken()
  const sessionId = generateId()
  const expiresAt = new Date(Date.now() + sessionTTL(kind))

  await db.insert(sessions).values({
    id: sessionId,
    user_id: userId,
    token_hash: tokenHash,
    kind,
    session_pubkey: serverPubkey,
    encrypted_org_keys: JSON.stringify(encryptedOrgKeys),
    created_at: new Date(),
    expires_at: expiresAt,
  })

  return { token, sessionId, expiresAt }
}

// createTokenSession stores a long-lived access token. The bearer half was
// just generated by the caller; encryptedOrgKeys are the caller's org keys
// re-wrapped under the token's own transport key, so `shh auth <token>` can
// decrypt without ever seeing a master password.
export async function createTokenSession(
  userId: string,
  name: string,
  encryptedOrgKeys: Record<string, string>,
  expiresAt: Date
): Promise<{ token: string; sessionId: string }> {
  const { token, tokenHash } = await newToken()
  const sessionId = generateId()

  await db.insert(sessions).values({
    id: sessionId,
    user_id: userId,
    token_hash: tokenHash,
    kind: 'token',
    name,
    // Tokens carry their transport key inline (the second half of the
    // displayed token) instead of deriving it via ECDH.
    session_pubkey: '',
    encrypted_org_keys: JSON.stringify(encryptedOrgKeys),
    created_at: new Date(),
    expires_at: expiresAt,
  })

  return { token, sessionId }
}

// rotateSessionToken issues a fresh token for a rolling (CLI) session and
// extends its expiry by the session TTL. The outgoing token is kept in
// prev_token_hash for a short grace window. The update is a compare-and-swap
// on the current token hash: if a concurrent request already rotated, this
// one loses cleanly (returns null) instead of clobbering the winner's token.
export async function rotateSessionToken(
  session: Session
): Promise<{ token: string; expiresAt: Date } | null> {
  const { token, tokenHash } = await newToken()
  const expiresAt = new Date(Date.now() + sessionTTL(session.kind as SessionKind))

  const updated = await db.update(sessions)
    .set({
      token_hash: tokenHash,
      prev_token_hash: session.token_hash,
      prev_token_expires_at: new Date(Date.now() + PREV_TOKEN_GRACE_MS),
      expires_at: expiresAt,
    })
    .where(and(
      eq(sessions.id, session.id),
      eq(sessions.token_hash, session.token_hash),
      isNull(sessions.revoked_at)
    ))
    .returning({ id: sessions.id })
  if (updated.length === 0) return null

  return { token, expiresAt }
}

export async function revokeSession(sessionId: string): Promise<void> {
  await db.update(sessions).set({ revoked_at: new Date() }).where(eq(sessions.id, sessionId))
}

// Kicks every other interactive login after a password change. Long-lived
// access tokens ('token' kind) survive on purpose: they are machine
// credentials with their own lifecycle (revocable on the tokens page), and
// the org keys they transport are unchanged by a password change.
export async function revokeOtherInteractiveSessions(userId: string, keepSessionId: string): Promise<void> {
  await db.update(sessions)
    .set({ revoked_at: new Date() })
    .where(and(
      eq(sessions.user_id, userId),
      ne(sessions.id, keepSessionId),
      inArray(sessions.kind, ['web', 'cli']),
      isNull(sessions.revoked_at)
    ))
}

export async function revokeAllUserSessions(userId: string): Promise<void> {
  await db.update(sessions)
    .set({ revoked_at: new Date() })
    .where(and(eq(sessions.user_id, userId), isNull(sessions.revoked_at)))
}
