/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardOrgIdIndexRouteImport } from './routes/dashboard/$orgId/index'
import { Route as ApiOrgsIndexRouteImport } from './routes/api/orgs/index'
import { Route as DashboardOrgIdSettingsRouteImport } from './routes/dashboard/$orgId/settings'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api/projects/$projectId'
import { Route as ApiOrgsOrgIdRouteImport } from './routes/api/orgs/$orgId'
import { Route as ApiEnvsEnvIdRouteImport } from './routes/api/envs/$envId'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api/auth/verify-email'
import { Route as ApiAuthResendVerificationRouteImport } from './routes/api/auth/resend-verification'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as DashboardOrgIdProjectIdIndexRouteImport } from './routes/dashboard/$orgId/$projectId/index'
import { Route as DashboardOrgIdProjectIdSettingsRouteImport } from './routes/dashboard/$orgId/$projectId/settings'
import { Route as ApiProjectsProjectIdEnvsRouteImport } from './routes/api/projects/$projectId.envs'
import { Route as ApiOrgsOrgIdProjectsRouteImport } from './routes/api/orgs/$orgId.projects'
import { Route as ApiOrgsOrgIdMembersRouteImport } from './routes/api/orgs/$orgId.members'
import { Route as ApiOrgsOrgIdKeyRouteImport } from './routes/api/orgs/$orgId.key'
import { Route as ApiOrgsOrgIdInviteRouteImport } from './routes/api/orgs/$orgId.invite'
import { Route as ApiEnvsEnvIdVarsRouteImport } from './routes/api/envs/$envId.vars'
import { Route as ApiEnvsEnvIdSecretsRouteImport } from './routes/api/envs/$envId.secrets'
import { Route as ApiEnvsEnvIdPermissionsRouteImport } from './routes/api/envs/$envId.permissions'
import { Route as ApiOrgsOrgIdMembersUserIdRouteImport } from './routes/api/orgs/$orgId.members.$userId'
import { Route as ApiEnvsEnvIdVarsKeyRouteImport } from './routes/api/envs/$envId.vars.$key'
import { Route as ApiEnvsEnvIdSecretsKeyRouteImport } from './routes/api/envs/$envId.secrets.$key'
import { Route as ApiEnvsEnvIdPermissionsUserIdRouteImport } from './routes/api/envs/$envId.permissions.$userId'
import { Route as ApiProjectsProjectIdEnvsEnvNamePullRouteImport } from './routes/api/projects/$projectId.envs.$envName.pull'
import { Route as ApiProjectsProjectIdEnvsEnvIdForkRouteImport } from './routes/api/projects/$projectId.envs.$envId.fork'
import { Route as ApiEnvsEnvIdVarsKeyRestoreRouteImport } from './routes/api/envs/$envId.vars.$key.restore'
import { Route as ApiEnvsEnvIdVarsKeyHistoryRouteImport } from './routes/api/envs/$envId.vars.$key.history'
import { Route as ApiEnvsEnvIdSecretsKeyRestoreRouteImport } from './routes/api/envs/$envId.secrets.$key.restore'
import { Route as ApiEnvsEnvIdSecretsKeyHistoryRouteImport } from './routes/api/envs/$envId.secrets.$key.history'
import { Route as ApiEnvsEnvIdSecretsKeyEncryptedRouteImport } from './routes/api/envs/$envId.secrets.$key.encrypted'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgIdIndexRoute = DashboardOrgIdIndexRouteImport.update({
  id: '/dashboard/$orgId/',
  path: '/dashboard/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgsIndexRoute = ApiOrgsIndexRouteImport.update({
  id: '/api/orgs/',
  path: '/api/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgIdSettingsRoute = DashboardOrgIdSettingsRouteImport.update({
  id: '/dashboard/$orgId/settings',
  path: '/dashboard/$orgId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/api/projects/$projectId',
  path: '/api/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgsOrgIdRoute = ApiOrgsOrgIdRouteImport.update({
  id: '/api/orgs/$orgId',
  path: '/api/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnvsEnvIdRoute = ApiEnvsEnvIdRouteImport.update({
  id: '/api/envs/$envId',
  path: '/api/envs/$envId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResendVerificationRoute =
  ApiAuthResendVerificationRouteImport.update({
    id: '/api/auth/resend-verification',
    path: '/api/auth/resend-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgIdProjectIdIndexRoute =
  DashboardOrgIdProjectIdIndexRouteImport.update({
    id: '/dashboard/$orgId/$projectId/',
    path: '/dashboard/$orgId/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardOrgIdProjectIdSettingsRoute =
  DashboardOrgIdProjectIdSettingsRouteImport.update({
    id: '/dashboard/$orgId/$projectId/settings',
    path: '/dashboard/$orgId/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdEnvsRoute =
  ApiProjectsProjectIdEnvsRouteImport.update({
    id: '/envs',
    path: '/envs',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiOrgsOrgIdProjectsRoute = ApiOrgsOrgIdProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ApiOrgsOrgIdRoute,
} as any)
const ApiOrgsOrgIdMembersRoute = ApiOrgsOrgIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiOrgsOrgIdRoute,
} as any)
const ApiOrgsOrgIdKeyRoute = ApiOrgsOrgIdKeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => ApiOrgsOrgIdRoute,
} as any)
const ApiOrgsOrgIdInviteRoute = ApiOrgsOrgIdInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => ApiOrgsOrgIdRoute,
} as any)
const ApiEnvsEnvIdVarsRoute = ApiEnvsEnvIdVarsRouteImport.update({
  id: '/vars',
  path: '/vars',
  getParentRoute: () => ApiEnvsEnvIdRoute,
} as any)
const ApiEnvsEnvIdSecretsRoute = ApiEnvsEnvIdSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => ApiEnvsEnvIdRoute,
} as any)
const ApiEnvsEnvIdPermissionsRoute = ApiEnvsEnvIdPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => ApiEnvsEnvIdRoute,
} as any)
const ApiOrgsOrgIdMembersUserIdRoute =
  ApiOrgsOrgIdMembersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ApiOrgsOrgIdMembersRoute,
  } as any)
const ApiEnvsEnvIdVarsKeyRoute = ApiEnvsEnvIdVarsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiEnvsEnvIdVarsRoute,
} as any)
const ApiEnvsEnvIdSecretsKeyRoute = ApiEnvsEnvIdSecretsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiEnvsEnvIdSecretsRoute,
} as any)
const ApiEnvsEnvIdPermissionsUserIdRoute =
  ApiEnvsEnvIdPermissionsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ApiEnvsEnvIdPermissionsRoute,
  } as any)
const ApiProjectsProjectIdEnvsEnvNamePullRoute =
  ApiProjectsProjectIdEnvsEnvNamePullRouteImport.update({
    id: '/$envName/pull',
    path: '/$envName/pull',
    getParentRoute: () => ApiProjectsProjectIdEnvsRoute,
  } as any)
const ApiProjectsProjectIdEnvsEnvIdForkRoute =
  ApiProjectsProjectIdEnvsEnvIdForkRouteImport.update({
    id: '/$envId/fork',
    path: '/$envId/fork',
    getParentRoute: () => ApiProjectsProjectIdEnvsRoute,
  } as any)
const ApiEnvsEnvIdVarsKeyRestoreRoute =
  ApiEnvsEnvIdVarsKeyRestoreRouteImport.update({
    id: '/restore',
    path: '/restore',
    getParentRoute: () => ApiEnvsEnvIdVarsKeyRoute,
  } as any)
const ApiEnvsEnvIdVarsKeyHistoryRoute =
  ApiEnvsEnvIdVarsKeyHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiEnvsEnvIdVarsKeyRoute,
  } as any)
const ApiEnvsEnvIdSecretsKeyRestoreRoute =
  ApiEnvsEnvIdSecretsKeyRestoreRouteImport.update({
    id: '/restore',
    path: '/restore',
    getParentRoute: () => ApiEnvsEnvIdSecretsKeyRoute,
  } as any)
const ApiEnvsEnvIdSecretsKeyHistoryRoute =
  ApiEnvsEnvIdSecretsKeyHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ApiEnvsEnvIdSecretsKeyRoute,
  } as any)
const ApiEnvsEnvIdSecretsKeyEncryptedRoute =
  ApiEnvsEnvIdSecretsKeyEncryptedRouteImport.update({
    id: '/encrypted',
    path: '/encrypted',
    getParentRoute: () => ApiEnvsEnvIdSecretsKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/envs/$envId': typeof ApiEnvsEnvIdRouteWithChildren
  '/api/orgs/$orgId': typeof ApiOrgsOrgIdRouteWithChildren
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/dashboard/$orgId/settings': typeof DashboardOrgIdSettingsRoute
  '/api/orgs/': typeof ApiOrgsIndexRoute
  '/dashboard/$orgId/': typeof DashboardOrgIdIndexRoute
  '/api/envs/$envId/permissions': typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  '/api/envs/$envId/secrets': typeof ApiEnvsEnvIdSecretsRouteWithChildren
  '/api/envs/$envId/vars': typeof ApiEnvsEnvIdVarsRouteWithChildren
  '/api/orgs/$orgId/invite': typeof ApiOrgsOrgIdInviteRoute
  '/api/orgs/$orgId/key': typeof ApiOrgsOrgIdKeyRoute
  '/api/orgs/$orgId/members': typeof ApiOrgsOrgIdMembersRouteWithChildren
  '/api/orgs/$orgId/projects': typeof ApiOrgsOrgIdProjectsRoute
  '/api/projects/$projectId/envs': typeof ApiProjectsProjectIdEnvsRouteWithChildren
  '/dashboard/$orgId/$projectId/settings': typeof DashboardOrgIdProjectIdSettingsRoute
  '/dashboard/$orgId/$projectId/': typeof DashboardOrgIdProjectIdIndexRoute
  '/api/envs/$envId/permissions/$userId': typeof ApiEnvsEnvIdPermissionsUserIdRoute
  '/api/envs/$envId/secrets/$key': typeof ApiEnvsEnvIdSecretsKeyRouteWithChildren
  '/api/envs/$envId/vars/$key': typeof ApiEnvsEnvIdVarsKeyRouteWithChildren
  '/api/orgs/$orgId/members/$userId': typeof ApiOrgsOrgIdMembersUserIdRoute
  '/api/envs/$envId/secrets/$key/encrypted': typeof ApiEnvsEnvIdSecretsKeyEncryptedRoute
  '/api/envs/$envId/secrets/$key/history': typeof ApiEnvsEnvIdSecretsKeyHistoryRoute
  '/api/envs/$envId/secrets/$key/restore': typeof ApiEnvsEnvIdSecretsKeyRestoreRoute
  '/api/envs/$envId/vars/$key/history': typeof ApiEnvsEnvIdVarsKeyHistoryRoute
  '/api/envs/$envId/vars/$key/restore': typeof ApiEnvsEnvIdVarsKeyRestoreRoute
  '/api/projects/$projectId/envs/$envId/fork': typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  '/api/projects/$projectId/envs/$envName/pull': typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/envs/$envId': typeof ApiEnvsEnvIdRouteWithChildren
  '/api/orgs/$orgId': typeof ApiOrgsOrgIdRouteWithChildren
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/dashboard/$orgId/settings': typeof DashboardOrgIdSettingsRoute
  '/api/orgs': typeof ApiOrgsIndexRoute
  '/dashboard/$orgId': typeof DashboardOrgIdIndexRoute
  '/api/envs/$envId/permissions': typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  '/api/envs/$envId/secrets': typeof ApiEnvsEnvIdSecretsRouteWithChildren
  '/api/envs/$envId/vars': typeof ApiEnvsEnvIdVarsRouteWithChildren
  '/api/orgs/$orgId/invite': typeof ApiOrgsOrgIdInviteRoute
  '/api/orgs/$orgId/key': typeof ApiOrgsOrgIdKeyRoute
  '/api/orgs/$orgId/members': typeof ApiOrgsOrgIdMembersRouteWithChildren
  '/api/orgs/$orgId/projects': typeof ApiOrgsOrgIdProjectsRoute
  '/api/projects/$projectId/envs': typeof ApiProjectsProjectIdEnvsRouteWithChildren
  '/dashboard/$orgId/$projectId/settings': typeof DashboardOrgIdProjectIdSettingsRoute
  '/dashboard/$orgId/$projectId': typeof DashboardOrgIdProjectIdIndexRoute
  '/api/envs/$envId/permissions/$userId': typeof ApiEnvsEnvIdPermissionsUserIdRoute
  '/api/envs/$envId/secrets/$key': typeof ApiEnvsEnvIdSecretsKeyRouteWithChildren
  '/api/envs/$envId/vars/$key': typeof ApiEnvsEnvIdVarsKeyRouteWithChildren
  '/api/orgs/$orgId/members/$userId': typeof ApiOrgsOrgIdMembersUserIdRoute
  '/api/envs/$envId/secrets/$key/encrypted': typeof ApiEnvsEnvIdSecretsKeyEncryptedRoute
  '/api/envs/$envId/secrets/$key/history': typeof ApiEnvsEnvIdSecretsKeyHistoryRoute
  '/api/envs/$envId/secrets/$key/restore': typeof ApiEnvsEnvIdSecretsKeyRestoreRoute
  '/api/envs/$envId/vars/$key/history': typeof ApiEnvsEnvIdVarsKeyHistoryRoute
  '/api/envs/$envId/vars/$key/restore': typeof ApiEnvsEnvIdVarsKeyRestoreRoute
  '/api/projects/$projectId/envs/$envId/fork': typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  '/api/projects/$projectId/envs/$envName/pull': typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/resend-verification': typeof ApiAuthResendVerificationRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/envs/$envId': typeof ApiEnvsEnvIdRouteWithChildren
  '/api/orgs/$orgId': typeof ApiOrgsOrgIdRouteWithChildren
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/dashboard/$orgId/settings': typeof DashboardOrgIdSettingsRoute
  '/api/orgs/': typeof ApiOrgsIndexRoute
  '/dashboard/$orgId/': typeof DashboardOrgIdIndexRoute
  '/api/envs/$envId/permissions': typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  '/api/envs/$envId/secrets': typeof ApiEnvsEnvIdSecretsRouteWithChildren
  '/api/envs/$envId/vars': typeof ApiEnvsEnvIdVarsRouteWithChildren
  '/api/orgs/$orgId/invite': typeof ApiOrgsOrgIdInviteRoute
  '/api/orgs/$orgId/key': typeof ApiOrgsOrgIdKeyRoute
  '/api/orgs/$orgId/members': typeof ApiOrgsOrgIdMembersRouteWithChildren
  '/api/orgs/$orgId/projects': typeof ApiOrgsOrgIdProjectsRoute
  '/api/projects/$projectId/envs': typeof ApiProjectsProjectIdEnvsRouteWithChildren
  '/dashboard/$orgId/$projectId/settings': typeof DashboardOrgIdProjectIdSettingsRoute
  '/dashboard/$orgId/$projectId/': typeof DashboardOrgIdProjectIdIndexRoute
  '/api/envs/$envId/permissions/$userId': typeof ApiEnvsEnvIdPermissionsUserIdRoute
  '/api/envs/$envId/secrets/$key': typeof ApiEnvsEnvIdSecretsKeyRouteWithChildren
  '/api/envs/$envId/vars/$key': typeof ApiEnvsEnvIdVarsKeyRouteWithChildren
  '/api/orgs/$orgId/members/$userId': typeof ApiOrgsOrgIdMembersUserIdRoute
  '/api/envs/$envId/secrets/$key/encrypted': typeof ApiEnvsEnvIdSecretsKeyEncryptedRoute
  '/api/envs/$envId/secrets/$key/history': typeof ApiEnvsEnvIdSecretsKeyHistoryRoute
  '/api/envs/$envId/secrets/$key/restore': typeof ApiEnvsEnvIdSecretsKeyRestoreRoute
  '/api/envs/$envId/vars/$key/history': typeof ApiEnvsEnvIdVarsKeyHistoryRoute
  '/api/envs/$envId/vars/$key/restore': typeof ApiEnvsEnvIdVarsKeyRestoreRoute
  '/api/projects/$projectId/envs/$envId/fork': typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  '/api/projects/$projectId/envs/$envName/pull': typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/api/health'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/resend-verification'
    | '/api/auth/verify-email'
    | '/api/envs/$envId'
    | '/api/orgs/$orgId'
    | '/api/projects/$projectId'
    | '/dashboard/$orgId/settings'
    | '/api/orgs/'
    | '/dashboard/$orgId/'
    | '/api/envs/$envId/permissions'
    | '/api/envs/$envId/secrets'
    | '/api/envs/$envId/vars'
    | '/api/orgs/$orgId/invite'
    | '/api/orgs/$orgId/key'
    | '/api/orgs/$orgId/members'
    | '/api/orgs/$orgId/projects'
    | '/api/projects/$projectId/envs'
    | '/dashboard/$orgId/$projectId/settings'
    | '/dashboard/$orgId/$projectId/'
    | '/api/envs/$envId/permissions/$userId'
    | '/api/envs/$envId/secrets/$key'
    | '/api/envs/$envId/vars/$key'
    | '/api/orgs/$orgId/members/$userId'
    | '/api/envs/$envId/secrets/$key/encrypted'
    | '/api/envs/$envId/secrets/$key/history'
    | '/api/envs/$envId/secrets/$key/restore'
    | '/api/envs/$envId/vars/$key/history'
    | '/api/envs/$envId/vars/$key/restore'
    | '/api/projects/$projectId/envs/$envId/fork'
    | '/api/projects/$projectId/envs/$envName/pull'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/api/health'
    | '/dashboard'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/resend-verification'
    | '/api/auth/verify-email'
    | '/api/envs/$envId'
    | '/api/orgs/$orgId'
    | '/api/projects/$projectId'
    | '/dashboard/$orgId/settings'
    | '/api/orgs'
    | '/dashboard/$orgId'
    | '/api/envs/$envId/permissions'
    | '/api/envs/$envId/secrets'
    | '/api/envs/$envId/vars'
    | '/api/orgs/$orgId/invite'
    | '/api/orgs/$orgId/key'
    | '/api/orgs/$orgId/members'
    | '/api/orgs/$orgId/projects'
    | '/api/projects/$projectId/envs'
    | '/dashboard/$orgId/$projectId/settings'
    | '/dashboard/$orgId/$projectId'
    | '/api/envs/$envId/permissions/$userId'
    | '/api/envs/$envId/secrets/$key'
    | '/api/envs/$envId/vars/$key'
    | '/api/orgs/$orgId/members/$userId'
    | '/api/envs/$envId/secrets/$key/encrypted'
    | '/api/envs/$envId/secrets/$key/history'
    | '/api/envs/$envId/secrets/$key/restore'
    | '/api/envs/$envId/vars/$key/history'
    | '/api/envs/$envId/vars/$key/restore'
    | '/api/projects/$projectId/envs/$envId/fork'
    | '/api/projects/$projectId/envs/$envName/pull'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/api/health'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/resend-verification'
    | '/api/auth/verify-email'
    | '/api/envs/$envId'
    | '/api/orgs/$orgId'
    | '/api/projects/$projectId'
    | '/dashboard/$orgId/settings'
    | '/api/orgs/'
    | '/dashboard/$orgId/'
    | '/api/envs/$envId/permissions'
    | '/api/envs/$envId/secrets'
    | '/api/envs/$envId/vars'
    | '/api/orgs/$orgId/invite'
    | '/api/orgs/$orgId/key'
    | '/api/orgs/$orgId/members'
    | '/api/orgs/$orgId/projects'
    | '/api/projects/$projectId/envs'
    | '/dashboard/$orgId/$projectId/settings'
    | '/dashboard/$orgId/$projectId/'
    | '/api/envs/$envId/permissions/$userId'
    | '/api/envs/$envId/secrets/$key'
    | '/api/envs/$envId/vars/$key'
    | '/api/orgs/$orgId/members/$userId'
    | '/api/envs/$envId/secrets/$key/encrypted'
    | '/api/envs/$envId/secrets/$key/history'
    | '/api/envs/$envId/secrets/$key/restore'
    | '/api/envs/$envId/vars/$key/history'
    | '/api/envs/$envId/vars/$key/restore'
    | '/api/projects/$projectId/envs/$envId/fork'
    | '/api/projects/$projectId/envs/$envName/pull'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthResendVerificationRoute: typeof ApiAuthResendVerificationRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
  ApiEnvsEnvIdRoute: typeof ApiEnvsEnvIdRouteWithChildren
  ApiOrgsOrgIdRoute: typeof ApiOrgsOrgIdRouteWithChildren
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRouteWithChildren
  DashboardOrgIdSettingsRoute: typeof DashboardOrgIdSettingsRoute
  ApiOrgsIndexRoute: typeof ApiOrgsIndexRoute
  DashboardOrgIdIndexRoute: typeof DashboardOrgIdIndexRoute
  DashboardOrgIdProjectIdSettingsRoute: typeof DashboardOrgIdProjectIdSettingsRoute
  DashboardOrgIdProjectIdIndexRoute: typeof DashboardOrgIdProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgId/': {
      id: '/dashboard/$orgId/'
      path: '/dashboard/$orgId'
      fullPath: '/dashboard/$orgId/'
      preLoaderRoute: typeof DashboardOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orgs/': {
      id: '/api/orgs/'
      path: '/api/orgs'
      fullPath: '/api/orgs/'
      preLoaderRoute: typeof ApiOrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgId/settings': {
      id: '/dashboard/$orgId/settings'
      path: '/dashboard/$orgId/settings'
      fullPath: '/dashboard/$orgId/settings'
      preLoaderRoute: typeof DashboardOrgIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/api/projects/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orgs/$orgId': {
      id: '/api/orgs/$orgId'
      path: '/api/orgs/$orgId'
      fullPath: '/api/orgs/$orgId'
      preLoaderRoute: typeof ApiOrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/envs/$envId': {
      id: '/api/envs/$envId'
      path: '/api/envs/$envId'
      fullPath: '/api/envs/$envId'
      preLoaderRoute: typeof ApiEnvsEnvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/resend-verification': {
      id: '/api/auth/resend-verification'
      path: '/api/auth/resend-verification'
      fullPath: '/api/auth/resend-verification'
      preLoaderRoute: typeof ApiAuthResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgId/$projectId/': {
      id: '/dashboard/$orgId/$projectId/'
      path: '/dashboard/$orgId/$projectId'
      fullPath: '/dashboard/$orgId/$projectId/'
      preLoaderRoute: typeof DashboardOrgIdProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgId/$projectId/settings': {
      id: '/dashboard/$orgId/$projectId/settings'
      path: '/dashboard/$orgId/$projectId/settings'
      fullPath: '/dashboard/$orgId/$projectId/settings'
      preLoaderRoute: typeof DashboardOrgIdProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/envs': {
      id: '/api/projects/$projectId/envs'
      path: '/envs'
      fullPath: '/api/projects/$projectId/envs'
      preLoaderRoute: typeof ApiProjectsProjectIdEnvsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/orgs/$orgId/projects': {
      id: '/api/orgs/$orgId/projects'
      path: '/projects'
      fullPath: '/api/orgs/$orgId/projects'
      preLoaderRoute: typeof ApiOrgsOrgIdProjectsRouteImport
      parentRoute: typeof ApiOrgsOrgIdRoute
    }
    '/api/orgs/$orgId/members': {
      id: '/api/orgs/$orgId/members'
      path: '/members'
      fullPath: '/api/orgs/$orgId/members'
      preLoaderRoute: typeof ApiOrgsOrgIdMembersRouteImport
      parentRoute: typeof ApiOrgsOrgIdRoute
    }
    '/api/orgs/$orgId/key': {
      id: '/api/orgs/$orgId/key'
      path: '/key'
      fullPath: '/api/orgs/$orgId/key'
      preLoaderRoute: typeof ApiOrgsOrgIdKeyRouteImport
      parentRoute: typeof ApiOrgsOrgIdRoute
    }
    '/api/orgs/$orgId/invite': {
      id: '/api/orgs/$orgId/invite'
      path: '/invite'
      fullPath: '/api/orgs/$orgId/invite'
      preLoaderRoute: typeof ApiOrgsOrgIdInviteRouteImport
      parentRoute: typeof ApiOrgsOrgIdRoute
    }
    '/api/envs/$envId/vars': {
      id: '/api/envs/$envId/vars'
      path: '/vars'
      fullPath: '/api/envs/$envId/vars'
      preLoaderRoute: typeof ApiEnvsEnvIdVarsRouteImport
      parentRoute: typeof ApiEnvsEnvIdRoute
    }
    '/api/envs/$envId/secrets': {
      id: '/api/envs/$envId/secrets'
      path: '/secrets'
      fullPath: '/api/envs/$envId/secrets'
      preLoaderRoute: typeof ApiEnvsEnvIdSecretsRouteImport
      parentRoute: typeof ApiEnvsEnvIdRoute
    }
    '/api/envs/$envId/permissions': {
      id: '/api/envs/$envId/permissions'
      path: '/permissions'
      fullPath: '/api/envs/$envId/permissions'
      preLoaderRoute: typeof ApiEnvsEnvIdPermissionsRouteImport
      parentRoute: typeof ApiEnvsEnvIdRoute
    }
    '/api/orgs/$orgId/members/$userId': {
      id: '/api/orgs/$orgId/members/$userId'
      path: '/$userId'
      fullPath: '/api/orgs/$orgId/members/$userId'
      preLoaderRoute: typeof ApiOrgsOrgIdMembersUserIdRouteImport
      parentRoute: typeof ApiOrgsOrgIdMembersRoute
    }
    '/api/envs/$envId/vars/$key': {
      id: '/api/envs/$envId/vars/$key'
      path: '/$key'
      fullPath: '/api/envs/$envId/vars/$key'
      preLoaderRoute: typeof ApiEnvsEnvIdVarsKeyRouteImport
      parentRoute: typeof ApiEnvsEnvIdVarsRoute
    }
    '/api/envs/$envId/secrets/$key': {
      id: '/api/envs/$envId/secrets/$key'
      path: '/$key'
      fullPath: '/api/envs/$envId/secrets/$key'
      preLoaderRoute: typeof ApiEnvsEnvIdSecretsKeyRouteImport
      parentRoute: typeof ApiEnvsEnvIdSecretsRoute
    }
    '/api/envs/$envId/permissions/$userId': {
      id: '/api/envs/$envId/permissions/$userId'
      path: '/$userId'
      fullPath: '/api/envs/$envId/permissions/$userId'
      preLoaderRoute: typeof ApiEnvsEnvIdPermissionsUserIdRouteImport
      parentRoute: typeof ApiEnvsEnvIdPermissionsRoute
    }
    '/api/projects/$projectId/envs/$envName/pull': {
      id: '/api/projects/$projectId/envs/$envName/pull'
      path: '/$envName/pull'
      fullPath: '/api/projects/$projectId/envs/$envName/pull'
      preLoaderRoute: typeof ApiProjectsProjectIdEnvsEnvNamePullRouteImport
      parentRoute: typeof ApiProjectsProjectIdEnvsRoute
    }
    '/api/projects/$projectId/envs/$envId/fork': {
      id: '/api/projects/$projectId/envs/$envId/fork'
      path: '/$envId/fork'
      fullPath: '/api/projects/$projectId/envs/$envId/fork'
      preLoaderRoute: typeof ApiProjectsProjectIdEnvsEnvIdForkRouteImport
      parentRoute: typeof ApiProjectsProjectIdEnvsRoute
    }
    '/api/envs/$envId/vars/$key/restore': {
      id: '/api/envs/$envId/vars/$key/restore'
      path: '/restore'
      fullPath: '/api/envs/$envId/vars/$key/restore'
      preLoaderRoute: typeof ApiEnvsEnvIdVarsKeyRestoreRouteImport
      parentRoute: typeof ApiEnvsEnvIdVarsKeyRoute
    }
    '/api/envs/$envId/vars/$key/history': {
      id: '/api/envs/$envId/vars/$key/history'
      path: '/history'
      fullPath: '/api/envs/$envId/vars/$key/history'
      preLoaderRoute: typeof ApiEnvsEnvIdVarsKeyHistoryRouteImport
      parentRoute: typeof ApiEnvsEnvIdVarsKeyRoute
    }
    '/api/envs/$envId/secrets/$key/restore': {
      id: '/api/envs/$envId/secrets/$key/restore'
      path: '/restore'
      fullPath: '/api/envs/$envId/secrets/$key/restore'
      preLoaderRoute: typeof ApiEnvsEnvIdSecretsKeyRestoreRouteImport
      parentRoute: typeof ApiEnvsEnvIdSecretsKeyRoute
    }
    '/api/envs/$envId/secrets/$key/history': {
      id: '/api/envs/$envId/secrets/$key/history'
      path: '/history'
      fullPath: '/api/envs/$envId/secrets/$key/history'
      preLoaderRoute: typeof ApiEnvsEnvIdSecretsKeyHistoryRouteImport
      parentRoute: typeof ApiEnvsEnvIdSecretsKeyRoute
    }
    '/api/envs/$envId/secrets/$key/encrypted': {
      id: '/api/envs/$envId/secrets/$key/encrypted'
      path: '/encrypted'
      fullPath: '/api/envs/$envId/secrets/$key/encrypted'
      preLoaderRoute: typeof ApiEnvsEnvIdSecretsKeyEncryptedRouteImport
      parentRoute: typeof ApiEnvsEnvIdSecretsKeyRoute
    }
  }
}

interface ApiEnvsEnvIdPermissionsRouteChildren {
  ApiEnvsEnvIdPermissionsUserIdRoute: typeof ApiEnvsEnvIdPermissionsUserIdRoute
}

const ApiEnvsEnvIdPermissionsRouteChildren: ApiEnvsEnvIdPermissionsRouteChildren =
  {
    ApiEnvsEnvIdPermissionsUserIdRoute: ApiEnvsEnvIdPermissionsUserIdRoute,
  }

const ApiEnvsEnvIdPermissionsRouteWithChildren =
  ApiEnvsEnvIdPermissionsRoute._addFileChildren(
    ApiEnvsEnvIdPermissionsRouteChildren,
  )

interface ApiEnvsEnvIdSecretsKeyRouteChildren {
  ApiEnvsEnvIdSecretsKeyEncryptedRoute: typeof ApiEnvsEnvIdSecretsKeyEncryptedRoute
  ApiEnvsEnvIdSecretsKeyHistoryRoute: typeof ApiEnvsEnvIdSecretsKeyHistoryRoute
  ApiEnvsEnvIdSecretsKeyRestoreRoute: typeof ApiEnvsEnvIdSecretsKeyRestoreRoute
}

const ApiEnvsEnvIdSecretsKeyRouteChildren: ApiEnvsEnvIdSecretsKeyRouteChildren =
  {
    ApiEnvsEnvIdSecretsKeyEncryptedRoute: ApiEnvsEnvIdSecretsKeyEncryptedRoute,
    ApiEnvsEnvIdSecretsKeyHistoryRoute: ApiEnvsEnvIdSecretsKeyHistoryRoute,
    ApiEnvsEnvIdSecretsKeyRestoreRoute: ApiEnvsEnvIdSecretsKeyRestoreRoute,
  }

const ApiEnvsEnvIdSecretsKeyRouteWithChildren =
  ApiEnvsEnvIdSecretsKeyRoute._addFileChildren(
    ApiEnvsEnvIdSecretsKeyRouteChildren,
  )

interface ApiEnvsEnvIdSecretsRouteChildren {
  ApiEnvsEnvIdSecretsKeyRoute: typeof ApiEnvsEnvIdSecretsKeyRouteWithChildren
}

const ApiEnvsEnvIdSecretsRouteChildren: ApiEnvsEnvIdSecretsRouteChildren = {
  ApiEnvsEnvIdSecretsKeyRoute: ApiEnvsEnvIdSecretsKeyRouteWithChildren,
}

const ApiEnvsEnvIdSecretsRouteWithChildren =
  ApiEnvsEnvIdSecretsRoute._addFileChildren(ApiEnvsEnvIdSecretsRouteChildren)

interface ApiEnvsEnvIdVarsKeyRouteChildren {
  ApiEnvsEnvIdVarsKeyHistoryRoute: typeof ApiEnvsEnvIdVarsKeyHistoryRoute
  ApiEnvsEnvIdVarsKeyRestoreRoute: typeof ApiEnvsEnvIdVarsKeyRestoreRoute
}

const ApiEnvsEnvIdVarsKeyRouteChildren: ApiEnvsEnvIdVarsKeyRouteChildren = {
  ApiEnvsEnvIdVarsKeyHistoryRoute: ApiEnvsEnvIdVarsKeyHistoryRoute,
  ApiEnvsEnvIdVarsKeyRestoreRoute: ApiEnvsEnvIdVarsKeyRestoreRoute,
}

const ApiEnvsEnvIdVarsKeyRouteWithChildren =
  ApiEnvsEnvIdVarsKeyRoute._addFileChildren(ApiEnvsEnvIdVarsKeyRouteChildren)

interface ApiEnvsEnvIdVarsRouteChildren {
  ApiEnvsEnvIdVarsKeyRoute: typeof ApiEnvsEnvIdVarsKeyRouteWithChildren
}

const ApiEnvsEnvIdVarsRouteChildren: ApiEnvsEnvIdVarsRouteChildren = {
  ApiEnvsEnvIdVarsKeyRoute: ApiEnvsEnvIdVarsKeyRouteWithChildren,
}

const ApiEnvsEnvIdVarsRouteWithChildren =
  ApiEnvsEnvIdVarsRoute._addFileChildren(ApiEnvsEnvIdVarsRouteChildren)

interface ApiEnvsEnvIdRouteChildren {
  ApiEnvsEnvIdPermissionsRoute: typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  ApiEnvsEnvIdSecretsRoute: typeof ApiEnvsEnvIdSecretsRouteWithChildren
  ApiEnvsEnvIdVarsRoute: typeof ApiEnvsEnvIdVarsRouteWithChildren
}

const ApiEnvsEnvIdRouteChildren: ApiEnvsEnvIdRouteChildren = {
  ApiEnvsEnvIdPermissionsRoute: ApiEnvsEnvIdPermissionsRouteWithChildren,
  ApiEnvsEnvIdSecretsRoute: ApiEnvsEnvIdSecretsRouteWithChildren,
  ApiEnvsEnvIdVarsRoute: ApiEnvsEnvIdVarsRouteWithChildren,
}

const ApiEnvsEnvIdRouteWithChildren = ApiEnvsEnvIdRoute._addFileChildren(
  ApiEnvsEnvIdRouteChildren,
)

interface ApiOrgsOrgIdMembersRouteChildren {
  ApiOrgsOrgIdMembersUserIdRoute: typeof ApiOrgsOrgIdMembersUserIdRoute
}

const ApiOrgsOrgIdMembersRouteChildren: ApiOrgsOrgIdMembersRouteChildren = {
  ApiOrgsOrgIdMembersUserIdRoute: ApiOrgsOrgIdMembersUserIdRoute,
}

const ApiOrgsOrgIdMembersRouteWithChildren =
  ApiOrgsOrgIdMembersRoute._addFileChildren(ApiOrgsOrgIdMembersRouteChildren)

interface ApiOrgsOrgIdRouteChildren {
  ApiOrgsOrgIdInviteRoute: typeof ApiOrgsOrgIdInviteRoute
  ApiOrgsOrgIdKeyRoute: typeof ApiOrgsOrgIdKeyRoute
  ApiOrgsOrgIdMembersRoute: typeof ApiOrgsOrgIdMembersRouteWithChildren
  ApiOrgsOrgIdProjectsRoute: typeof ApiOrgsOrgIdProjectsRoute
}

const ApiOrgsOrgIdRouteChildren: ApiOrgsOrgIdRouteChildren = {
  ApiOrgsOrgIdInviteRoute: ApiOrgsOrgIdInviteRoute,
  ApiOrgsOrgIdKeyRoute: ApiOrgsOrgIdKeyRoute,
  ApiOrgsOrgIdMembersRoute: ApiOrgsOrgIdMembersRouteWithChildren,
  ApiOrgsOrgIdProjectsRoute: ApiOrgsOrgIdProjectsRoute,
}

const ApiOrgsOrgIdRouteWithChildren = ApiOrgsOrgIdRoute._addFileChildren(
  ApiOrgsOrgIdRouteChildren,
)

interface ApiProjectsProjectIdEnvsRouteChildren {
  ApiProjectsProjectIdEnvsEnvIdForkRoute: typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  ApiProjectsProjectIdEnvsEnvNamePullRoute: typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}

const ApiProjectsProjectIdEnvsRouteChildren: ApiProjectsProjectIdEnvsRouteChildren =
  {
    ApiProjectsProjectIdEnvsEnvIdForkRoute:
      ApiProjectsProjectIdEnvsEnvIdForkRoute,
    ApiProjectsProjectIdEnvsEnvNamePullRoute:
      ApiProjectsProjectIdEnvsEnvNamePullRoute,
  }

const ApiProjectsProjectIdEnvsRouteWithChildren =
  ApiProjectsProjectIdEnvsRoute._addFileChildren(
    ApiProjectsProjectIdEnvsRouteChildren,
  )

interface ApiProjectsProjectIdRouteChildren {
  ApiProjectsProjectIdEnvsRoute: typeof ApiProjectsProjectIdEnvsRouteWithChildren
}

const ApiProjectsProjectIdRouteChildren: ApiProjectsProjectIdRouteChildren = {
  ApiProjectsProjectIdEnvsRoute: ApiProjectsProjectIdEnvsRouteWithChildren,
}

const ApiProjectsProjectIdRouteWithChildren =
  ApiProjectsProjectIdRoute._addFileChildren(ApiProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiHealthRoute: ApiHealthRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthResendVerificationRoute: ApiAuthResendVerificationRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
  ApiEnvsEnvIdRoute: ApiEnvsEnvIdRouteWithChildren,
  ApiOrgsOrgIdRoute: ApiOrgsOrgIdRouteWithChildren,
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRouteWithChildren,
  DashboardOrgIdSettingsRoute: DashboardOrgIdSettingsRoute,
  ApiOrgsIndexRoute: ApiOrgsIndexRoute,
  DashboardOrgIdIndexRoute: DashboardOrgIdIndexRoute,
  DashboardOrgIdProjectIdSettingsRoute: DashboardOrgIdProjectIdSettingsRoute,
  DashboardOrgIdProjectIdIndexRoute: DashboardOrgIdProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
