/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardOrgIdIndexRouteImport } from './routes/dashboard/$orgId/index'
import { Route as ApiOrgsIndexRouteImport } from './routes/api/orgs/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as OrgsOrgIdSettingsRouteImport } from './routes/orgs/$orgId/settings'
import { Route as DashboardOrgIdProjectIdRouteImport } from './routes/dashboard/$orgId/$projectId'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api/projects/$projectId'
import { Route as ApiOrgsOrgIdRouteImport } from './routes/api/orgs/$orgId'
import { Route as ApiEnvsEnvIdRouteImport } from './routes/api/envs/$envId'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiProjectsProjectIdEnvsRouteImport } from './routes/api/projects/$projectId.envs'
import { Route as ApiOrgsOrgIdProjectsRouteImport } from './routes/api/orgs/$orgId.projects'
import { Route as ApiOrgsOrgIdMembersRouteImport } from './routes/api/orgs/$orgId.members'
import { Route as ApiOrgsOrgIdInviteRouteImport } from './routes/api/orgs/$orgId.invite'
import { Route as ApiEnvsEnvIdVarsRouteImport } from './routes/api/envs/$envId.vars'
import { Route as ApiEnvsEnvIdSecretsRouteImport } from './routes/api/envs/$envId.secrets'
import { Route as ApiEnvsEnvIdPermissionsRouteImport } from './routes/api/envs/$envId.permissions'
import { Route as ApiOrgsOrgIdMembersUserIdRouteImport } from './routes/api/orgs/$orgId.members.$userId'
import { Route as ApiEnvsEnvIdVarsKeyRouteImport } from './routes/api/envs/$envId.vars.$key'
import { Route as ApiEnvsEnvIdSecretsKeyRouteImport } from './routes/api/envs/$envId.secrets.$key'
import { Route as ApiEnvsEnvIdPermissionsUserIdRouteImport } from './routes/api/envs/$envId.permissions.$userId'
import { Route as ApiProjectsProjectIdEnvsEnvNamePullRouteImport } from './routes/api/projects/$projectId.envs.$envName.pull'
import { Route as ApiProjectsProjectIdEnvsEnvIdForkRouteImport } from './routes/api/projects/$projectId.envs.$envId.fork'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgIdIndexRoute = DashboardOrgIdIndexRouteImport.update({
  id: '/dashboard/$orgId/',
  path: '/dashboard/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgsIndexRoute = ApiOrgsIndexRouteImport.update({
  id: '/api/orgs/',
  path: '/api/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgIdSettingsRoute = OrgsOrgIdSettingsRouteImport.update({
  id: '/orgs/$orgId/settings',
  path: '/orgs/$orgId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgIdProjectIdRoute = DashboardOrgIdProjectIdRouteImport.update({
  id: '/dashboard/$orgId/$projectId',
  path: '/dashboard/$orgId/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/api/projects/$projectId',
  path: '/api/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgsOrgIdRoute = ApiOrgsOrgIdRouteImport.update({
  id: '/api/orgs/$orgId',
  path: '/api/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnvsEnvIdRoute = ApiEnvsEnvIdRouteImport.update({
  id: '/api/envs/$envId',
  path: '/api/envs/$envId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsProjectIdEnvsRoute =
  ApiProjectsProjectIdEnvsRouteImport.update({
    id: '/envs',
    path: '/envs',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiOrgsOrgIdProjectsRoute = ApiOrgsOrgIdProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ApiOrgsOrgIdRoute,
} as any)
const ApiOrgsOrgIdMembersRoute = ApiOrgsOrgIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiOrgsOrgIdRoute,
} as any)
const ApiOrgsOrgIdInviteRoute = ApiOrgsOrgIdInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => ApiOrgsOrgIdRoute,
} as any)
const ApiEnvsEnvIdVarsRoute = ApiEnvsEnvIdVarsRouteImport.update({
  id: '/vars',
  path: '/vars',
  getParentRoute: () => ApiEnvsEnvIdRoute,
} as any)
const ApiEnvsEnvIdSecretsRoute = ApiEnvsEnvIdSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => ApiEnvsEnvIdRoute,
} as any)
const ApiEnvsEnvIdPermissionsRoute = ApiEnvsEnvIdPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => ApiEnvsEnvIdRoute,
} as any)
const ApiOrgsOrgIdMembersUserIdRoute =
  ApiOrgsOrgIdMembersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ApiOrgsOrgIdMembersRoute,
  } as any)
const ApiEnvsEnvIdVarsKeyRoute = ApiEnvsEnvIdVarsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiEnvsEnvIdVarsRoute,
} as any)
const ApiEnvsEnvIdSecretsKeyRoute = ApiEnvsEnvIdSecretsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiEnvsEnvIdSecretsRoute,
} as any)
const ApiEnvsEnvIdPermissionsUserIdRoute =
  ApiEnvsEnvIdPermissionsUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => ApiEnvsEnvIdPermissionsRoute,
  } as any)
const ApiProjectsProjectIdEnvsEnvNamePullRoute =
  ApiProjectsProjectIdEnvsEnvNamePullRouteImport.update({
    id: '/$envName/pull',
    path: '/$envName/pull',
    getParentRoute: () => ApiProjectsProjectIdEnvsRoute,
  } as any)
const ApiProjectsProjectIdEnvsEnvIdForkRoute =
  ApiProjectsProjectIdEnvsEnvIdForkRouteImport.update({
    id: '/$envId/fork',
    path: '/$envId/fork',
    getParentRoute: () => ApiProjectsProjectIdEnvsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/envs/$envId': typeof ApiEnvsEnvIdRouteWithChildren
  '/api/orgs/$orgId': typeof ApiOrgsOrgIdRouteWithChildren
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/dashboard/$orgId/$projectId': typeof DashboardOrgIdProjectIdRoute
  '/orgs/$orgId/settings': typeof OrgsOrgIdSettingsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/api/orgs/': typeof ApiOrgsIndexRoute
  '/dashboard/$orgId/': typeof DashboardOrgIdIndexRoute
  '/api/envs/$envId/permissions': typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  '/api/envs/$envId/secrets': typeof ApiEnvsEnvIdSecretsRouteWithChildren
  '/api/envs/$envId/vars': typeof ApiEnvsEnvIdVarsRouteWithChildren
  '/api/orgs/$orgId/invite': typeof ApiOrgsOrgIdInviteRoute
  '/api/orgs/$orgId/members': typeof ApiOrgsOrgIdMembersRouteWithChildren
  '/api/orgs/$orgId/projects': typeof ApiOrgsOrgIdProjectsRoute
  '/api/projects/$projectId/envs': typeof ApiProjectsProjectIdEnvsRouteWithChildren
  '/api/envs/$envId/permissions/$userId': typeof ApiEnvsEnvIdPermissionsUserIdRoute
  '/api/envs/$envId/secrets/$key': typeof ApiEnvsEnvIdSecretsKeyRoute
  '/api/envs/$envId/vars/$key': typeof ApiEnvsEnvIdVarsKeyRoute
  '/api/orgs/$orgId/members/$userId': typeof ApiOrgsOrgIdMembersUserIdRoute
  '/api/projects/$projectId/envs/$envId/fork': typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  '/api/projects/$projectId/envs/$envName/pull': typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/envs/$envId': typeof ApiEnvsEnvIdRouteWithChildren
  '/api/orgs/$orgId': typeof ApiOrgsOrgIdRouteWithChildren
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/dashboard/$orgId/$projectId': typeof DashboardOrgIdProjectIdRoute
  '/orgs/$orgId/settings': typeof OrgsOrgIdSettingsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/api/orgs': typeof ApiOrgsIndexRoute
  '/dashboard/$orgId': typeof DashboardOrgIdIndexRoute
  '/api/envs/$envId/permissions': typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  '/api/envs/$envId/secrets': typeof ApiEnvsEnvIdSecretsRouteWithChildren
  '/api/envs/$envId/vars': typeof ApiEnvsEnvIdVarsRouteWithChildren
  '/api/orgs/$orgId/invite': typeof ApiOrgsOrgIdInviteRoute
  '/api/orgs/$orgId/members': typeof ApiOrgsOrgIdMembersRouteWithChildren
  '/api/orgs/$orgId/projects': typeof ApiOrgsOrgIdProjectsRoute
  '/api/projects/$projectId/envs': typeof ApiProjectsProjectIdEnvsRouteWithChildren
  '/api/envs/$envId/permissions/$userId': typeof ApiEnvsEnvIdPermissionsUserIdRoute
  '/api/envs/$envId/secrets/$key': typeof ApiEnvsEnvIdSecretsKeyRoute
  '/api/envs/$envId/vars/$key': typeof ApiEnvsEnvIdVarsKeyRoute
  '/api/orgs/$orgId/members/$userId': typeof ApiOrgsOrgIdMembersUserIdRoute
  '/api/projects/$projectId/envs/$envId/fork': typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  '/api/projects/$projectId/envs/$envName/pull': typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/envs/$envId': typeof ApiEnvsEnvIdRouteWithChildren
  '/api/orgs/$orgId': typeof ApiOrgsOrgIdRouteWithChildren
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/dashboard/$orgId/$projectId': typeof DashboardOrgIdProjectIdRoute
  '/orgs/$orgId/settings': typeof OrgsOrgIdSettingsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/api/orgs/': typeof ApiOrgsIndexRoute
  '/dashboard/$orgId/': typeof DashboardOrgIdIndexRoute
  '/api/envs/$envId/permissions': typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  '/api/envs/$envId/secrets': typeof ApiEnvsEnvIdSecretsRouteWithChildren
  '/api/envs/$envId/vars': typeof ApiEnvsEnvIdVarsRouteWithChildren
  '/api/orgs/$orgId/invite': typeof ApiOrgsOrgIdInviteRoute
  '/api/orgs/$orgId/members': typeof ApiOrgsOrgIdMembersRouteWithChildren
  '/api/orgs/$orgId/projects': typeof ApiOrgsOrgIdProjectsRoute
  '/api/projects/$projectId/envs': typeof ApiProjectsProjectIdEnvsRouteWithChildren
  '/api/envs/$envId/permissions/$userId': typeof ApiEnvsEnvIdPermissionsUserIdRoute
  '/api/envs/$envId/secrets/$key': typeof ApiEnvsEnvIdSecretsKeyRoute
  '/api/envs/$envId/vars/$key': typeof ApiEnvsEnvIdVarsKeyRoute
  '/api/orgs/$orgId/members/$userId': typeof ApiOrgsOrgIdMembersUserIdRoute
  '/api/projects/$projectId/envs/$envId/fork': typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  '/api/projects/$projectId/envs/$envName/pull': typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/health'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/envs/$envId'
    | '/api/orgs/$orgId'
    | '/api/projects/$projectId'
    | '/dashboard/$orgId/$projectId'
    | '/orgs/$orgId/settings'
    | '/projects/$projectId/settings'
    | '/api/orgs/'
    | '/dashboard/$orgId/'
    | '/api/envs/$envId/permissions'
    | '/api/envs/$envId/secrets'
    | '/api/envs/$envId/vars'
    | '/api/orgs/$orgId/invite'
    | '/api/orgs/$orgId/members'
    | '/api/orgs/$orgId/projects'
    | '/api/projects/$projectId/envs'
    | '/api/envs/$envId/permissions/$userId'
    | '/api/envs/$envId/secrets/$key'
    | '/api/envs/$envId/vars/$key'
    | '/api/orgs/$orgId/members/$userId'
    | '/api/projects/$projectId/envs/$envId/fork'
    | '/api/projects/$projectId/envs/$envName/pull'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/health'
    | '/dashboard'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/envs/$envId'
    | '/api/orgs/$orgId'
    | '/api/projects/$projectId'
    | '/dashboard/$orgId/$projectId'
    | '/orgs/$orgId/settings'
    | '/projects/$projectId/settings'
    | '/api/orgs'
    | '/dashboard/$orgId'
    | '/api/envs/$envId/permissions'
    | '/api/envs/$envId/secrets'
    | '/api/envs/$envId/vars'
    | '/api/orgs/$orgId/invite'
    | '/api/orgs/$orgId/members'
    | '/api/orgs/$orgId/projects'
    | '/api/projects/$projectId/envs'
    | '/api/envs/$envId/permissions/$userId'
    | '/api/envs/$envId/secrets/$key'
    | '/api/envs/$envId/vars/$key'
    | '/api/orgs/$orgId/members/$userId'
    | '/api/projects/$projectId/envs/$envId/fork'
    | '/api/projects/$projectId/envs/$envName/pull'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/api/health'
    | '/dashboard/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/envs/$envId'
    | '/api/orgs/$orgId'
    | '/api/projects/$projectId'
    | '/dashboard/$orgId/$projectId'
    | '/orgs/$orgId/settings'
    | '/projects/$projectId/settings'
    | '/api/orgs/'
    | '/dashboard/$orgId/'
    | '/api/envs/$envId/permissions'
    | '/api/envs/$envId/secrets'
    | '/api/envs/$envId/vars'
    | '/api/orgs/$orgId/invite'
    | '/api/orgs/$orgId/members'
    | '/api/orgs/$orgId/projects'
    | '/api/projects/$projectId/envs'
    | '/api/envs/$envId/permissions/$userId'
    | '/api/envs/$envId/secrets/$key'
    | '/api/envs/$envId/vars/$key'
    | '/api/orgs/$orgId/members/$userId'
    | '/api/projects/$projectId/envs/$envId/fork'
    | '/api/projects/$projectId/envs/$envName/pull'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiEnvsEnvIdRoute: typeof ApiEnvsEnvIdRouteWithChildren
  ApiOrgsOrgIdRoute: typeof ApiOrgsOrgIdRouteWithChildren
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRouteWithChildren
  DashboardOrgIdProjectIdRoute: typeof DashboardOrgIdProjectIdRoute
  OrgsOrgIdSettingsRoute: typeof OrgsOrgIdSettingsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ApiOrgsIndexRoute: typeof ApiOrgsIndexRoute
  DashboardOrgIdIndexRoute: typeof DashboardOrgIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgId/': {
      id: '/dashboard/$orgId/'
      path: '/dashboard/$orgId'
      fullPath: '/dashboard/$orgId/'
      preLoaderRoute: typeof DashboardOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orgs/': {
      id: '/api/orgs/'
      path: '/api/orgs'
      fullPath: '/api/orgs/'
      preLoaderRoute: typeof ApiOrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/settings': {
      id: '/orgs/$orgId/settings'
      path: '/orgs/$orgId/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof OrgsOrgIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgId/$projectId': {
      id: '/dashboard/$orgId/$projectId'
      path: '/dashboard/$orgId/$projectId'
      fullPath: '/dashboard/$orgId/$projectId'
      preLoaderRoute: typeof DashboardOrgIdProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/api/projects/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orgs/$orgId': {
      id: '/api/orgs/$orgId'
      path: '/api/orgs/$orgId'
      fullPath: '/api/orgs/$orgId'
      preLoaderRoute: typeof ApiOrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/envs/$envId': {
      id: '/api/envs/$envId'
      path: '/api/envs/$envId'
      fullPath: '/api/envs/$envId'
      preLoaderRoute: typeof ApiEnvsEnvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/envs': {
      id: '/api/projects/$projectId/envs'
      path: '/envs'
      fullPath: '/api/projects/$projectId/envs'
      preLoaderRoute: typeof ApiProjectsProjectIdEnvsRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/orgs/$orgId/projects': {
      id: '/api/orgs/$orgId/projects'
      path: '/projects'
      fullPath: '/api/orgs/$orgId/projects'
      preLoaderRoute: typeof ApiOrgsOrgIdProjectsRouteImport
      parentRoute: typeof ApiOrgsOrgIdRoute
    }
    '/api/orgs/$orgId/members': {
      id: '/api/orgs/$orgId/members'
      path: '/members'
      fullPath: '/api/orgs/$orgId/members'
      preLoaderRoute: typeof ApiOrgsOrgIdMembersRouteImport
      parentRoute: typeof ApiOrgsOrgIdRoute
    }
    '/api/orgs/$orgId/invite': {
      id: '/api/orgs/$orgId/invite'
      path: '/invite'
      fullPath: '/api/orgs/$orgId/invite'
      preLoaderRoute: typeof ApiOrgsOrgIdInviteRouteImport
      parentRoute: typeof ApiOrgsOrgIdRoute
    }
    '/api/envs/$envId/vars': {
      id: '/api/envs/$envId/vars'
      path: '/vars'
      fullPath: '/api/envs/$envId/vars'
      preLoaderRoute: typeof ApiEnvsEnvIdVarsRouteImport
      parentRoute: typeof ApiEnvsEnvIdRoute
    }
    '/api/envs/$envId/secrets': {
      id: '/api/envs/$envId/secrets'
      path: '/secrets'
      fullPath: '/api/envs/$envId/secrets'
      preLoaderRoute: typeof ApiEnvsEnvIdSecretsRouteImport
      parentRoute: typeof ApiEnvsEnvIdRoute
    }
    '/api/envs/$envId/permissions': {
      id: '/api/envs/$envId/permissions'
      path: '/permissions'
      fullPath: '/api/envs/$envId/permissions'
      preLoaderRoute: typeof ApiEnvsEnvIdPermissionsRouteImport
      parentRoute: typeof ApiEnvsEnvIdRoute
    }
    '/api/orgs/$orgId/members/$userId': {
      id: '/api/orgs/$orgId/members/$userId'
      path: '/$userId'
      fullPath: '/api/orgs/$orgId/members/$userId'
      preLoaderRoute: typeof ApiOrgsOrgIdMembersUserIdRouteImport
      parentRoute: typeof ApiOrgsOrgIdMembersRoute
    }
    '/api/envs/$envId/vars/$key': {
      id: '/api/envs/$envId/vars/$key'
      path: '/$key'
      fullPath: '/api/envs/$envId/vars/$key'
      preLoaderRoute: typeof ApiEnvsEnvIdVarsKeyRouteImport
      parentRoute: typeof ApiEnvsEnvIdVarsRoute
    }
    '/api/envs/$envId/secrets/$key': {
      id: '/api/envs/$envId/secrets/$key'
      path: '/$key'
      fullPath: '/api/envs/$envId/secrets/$key'
      preLoaderRoute: typeof ApiEnvsEnvIdSecretsKeyRouteImport
      parentRoute: typeof ApiEnvsEnvIdSecretsRoute
    }
    '/api/envs/$envId/permissions/$userId': {
      id: '/api/envs/$envId/permissions/$userId'
      path: '/$userId'
      fullPath: '/api/envs/$envId/permissions/$userId'
      preLoaderRoute: typeof ApiEnvsEnvIdPermissionsUserIdRouteImport
      parentRoute: typeof ApiEnvsEnvIdPermissionsRoute
    }
    '/api/projects/$projectId/envs/$envName/pull': {
      id: '/api/projects/$projectId/envs/$envName/pull'
      path: '/$envName/pull'
      fullPath: '/api/projects/$projectId/envs/$envName/pull'
      preLoaderRoute: typeof ApiProjectsProjectIdEnvsEnvNamePullRouteImport
      parentRoute: typeof ApiProjectsProjectIdEnvsRoute
    }
    '/api/projects/$projectId/envs/$envId/fork': {
      id: '/api/projects/$projectId/envs/$envId/fork'
      path: '/$envId/fork'
      fullPath: '/api/projects/$projectId/envs/$envId/fork'
      preLoaderRoute: typeof ApiProjectsProjectIdEnvsEnvIdForkRouteImport
      parentRoute: typeof ApiProjectsProjectIdEnvsRoute
    }
  }
}

interface ApiEnvsEnvIdPermissionsRouteChildren {
  ApiEnvsEnvIdPermissionsUserIdRoute: typeof ApiEnvsEnvIdPermissionsUserIdRoute
}

const ApiEnvsEnvIdPermissionsRouteChildren: ApiEnvsEnvIdPermissionsRouteChildren =
  {
    ApiEnvsEnvIdPermissionsUserIdRoute: ApiEnvsEnvIdPermissionsUserIdRoute,
  }

const ApiEnvsEnvIdPermissionsRouteWithChildren =
  ApiEnvsEnvIdPermissionsRoute._addFileChildren(
    ApiEnvsEnvIdPermissionsRouteChildren,
  )

interface ApiEnvsEnvIdSecretsRouteChildren {
  ApiEnvsEnvIdSecretsKeyRoute: typeof ApiEnvsEnvIdSecretsKeyRoute
}

const ApiEnvsEnvIdSecretsRouteChildren: ApiEnvsEnvIdSecretsRouteChildren = {
  ApiEnvsEnvIdSecretsKeyRoute: ApiEnvsEnvIdSecretsKeyRoute,
}

const ApiEnvsEnvIdSecretsRouteWithChildren =
  ApiEnvsEnvIdSecretsRoute._addFileChildren(ApiEnvsEnvIdSecretsRouteChildren)

interface ApiEnvsEnvIdVarsRouteChildren {
  ApiEnvsEnvIdVarsKeyRoute: typeof ApiEnvsEnvIdVarsKeyRoute
}

const ApiEnvsEnvIdVarsRouteChildren: ApiEnvsEnvIdVarsRouteChildren = {
  ApiEnvsEnvIdVarsKeyRoute: ApiEnvsEnvIdVarsKeyRoute,
}

const ApiEnvsEnvIdVarsRouteWithChildren =
  ApiEnvsEnvIdVarsRoute._addFileChildren(ApiEnvsEnvIdVarsRouteChildren)

interface ApiEnvsEnvIdRouteChildren {
  ApiEnvsEnvIdPermissionsRoute: typeof ApiEnvsEnvIdPermissionsRouteWithChildren
  ApiEnvsEnvIdSecretsRoute: typeof ApiEnvsEnvIdSecretsRouteWithChildren
  ApiEnvsEnvIdVarsRoute: typeof ApiEnvsEnvIdVarsRouteWithChildren
}

const ApiEnvsEnvIdRouteChildren: ApiEnvsEnvIdRouteChildren = {
  ApiEnvsEnvIdPermissionsRoute: ApiEnvsEnvIdPermissionsRouteWithChildren,
  ApiEnvsEnvIdSecretsRoute: ApiEnvsEnvIdSecretsRouteWithChildren,
  ApiEnvsEnvIdVarsRoute: ApiEnvsEnvIdVarsRouteWithChildren,
}

const ApiEnvsEnvIdRouteWithChildren = ApiEnvsEnvIdRoute._addFileChildren(
  ApiEnvsEnvIdRouteChildren,
)

interface ApiOrgsOrgIdMembersRouteChildren {
  ApiOrgsOrgIdMembersUserIdRoute: typeof ApiOrgsOrgIdMembersUserIdRoute
}

const ApiOrgsOrgIdMembersRouteChildren: ApiOrgsOrgIdMembersRouteChildren = {
  ApiOrgsOrgIdMembersUserIdRoute: ApiOrgsOrgIdMembersUserIdRoute,
}

const ApiOrgsOrgIdMembersRouteWithChildren =
  ApiOrgsOrgIdMembersRoute._addFileChildren(ApiOrgsOrgIdMembersRouteChildren)

interface ApiOrgsOrgIdRouteChildren {
  ApiOrgsOrgIdInviteRoute: typeof ApiOrgsOrgIdInviteRoute
  ApiOrgsOrgIdMembersRoute: typeof ApiOrgsOrgIdMembersRouteWithChildren
  ApiOrgsOrgIdProjectsRoute: typeof ApiOrgsOrgIdProjectsRoute
}

const ApiOrgsOrgIdRouteChildren: ApiOrgsOrgIdRouteChildren = {
  ApiOrgsOrgIdInviteRoute: ApiOrgsOrgIdInviteRoute,
  ApiOrgsOrgIdMembersRoute: ApiOrgsOrgIdMembersRouteWithChildren,
  ApiOrgsOrgIdProjectsRoute: ApiOrgsOrgIdProjectsRoute,
}

const ApiOrgsOrgIdRouteWithChildren = ApiOrgsOrgIdRoute._addFileChildren(
  ApiOrgsOrgIdRouteChildren,
)

interface ApiProjectsProjectIdEnvsRouteChildren {
  ApiProjectsProjectIdEnvsEnvIdForkRoute: typeof ApiProjectsProjectIdEnvsEnvIdForkRoute
  ApiProjectsProjectIdEnvsEnvNamePullRoute: typeof ApiProjectsProjectIdEnvsEnvNamePullRoute
}

const ApiProjectsProjectIdEnvsRouteChildren: ApiProjectsProjectIdEnvsRouteChildren =
  {
    ApiProjectsProjectIdEnvsEnvIdForkRoute:
      ApiProjectsProjectIdEnvsEnvIdForkRoute,
    ApiProjectsProjectIdEnvsEnvNamePullRoute:
      ApiProjectsProjectIdEnvsEnvNamePullRoute,
  }

const ApiProjectsProjectIdEnvsRouteWithChildren =
  ApiProjectsProjectIdEnvsRoute._addFileChildren(
    ApiProjectsProjectIdEnvsRouteChildren,
  )

interface ApiProjectsProjectIdRouteChildren {
  ApiProjectsProjectIdEnvsRoute: typeof ApiProjectsProjectIdEnvsRouteWithChildren
}

const ApiProjectsProjectIdRouteChildren: ApiProjectsProjectIdRouteChildren = {
  ApiProjectsProjectIdEnvsRoute: ApiProjectsProjectIdEnvsRouteWithChildren,
}

const ApiProjectsProjectIdRouteWithChildren =
  ApiProjectsProjectIdRoute._addFileChildren(ApiProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiEnvsEnvIdRoute: ApiEnvsEnvIdRouteWithChildren,
  ApiOrgsOrgIdRoute: ApiOrgsOrgIdRouteWithChildren,
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRouteWithChildren,
  DashboardOrgIdProjectIdRoute: DashboardOrgIdProjectIdRoute,
  OrgsOrgIdSettingsRoute: OrgsOrgIdSettingsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ApiOrgsIndexRoute: ApiOrgsIndexRoute,
  DashboardOrgIdIndexRoute: DashboardOrgIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
